dbt_pipeline:
  outputs:
    dev:
      dataset: jaffle_shop
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\thana\OneDrive\Documents\dbt-project\KEY\test-dbt-393206-key.json
      location: US
      method: service-account
      priority: interactive
      project: test-dbt-393206
      threads: 1
      type: bigquery
  target: dev
